### ISSUE TITLE
Error evaluating R50 DeAOTL + RMem model

### ISSUE THREAD

**Issue by MZhengRPI** [Restricted-Memory/RMem#4]
Hi! It seems like I am getting error when running ./eval_vost.sh with "model="r50_deaotl" and checkpoint path set to "--ckpt_path pretrain_models/aotplus_R50_DeOTL_Temp_pe_Slot_4_ema_20000.pth", 
“Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "RMem/aot_plus/tools/eval.py", line 48, in main_worker
    evaluator.evaluating()
  File "RMem/aot_plus/./networks/managers/evaluator.py", line 475, in evaluating
    attn_values = np.reshape(lstt_layer.short_attn_values, (h, w, -1))
  File "<__array_function__ internals>", line 180, in reshape
  File "/usr/local/lib/python3.8/dist-packages/numpy/core/fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/usr/local/lib/python3.8/dist-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 7200 into shape (37,66,newaxis)”

May I try to get suggestions c.f. how to solve this problem? Thank you so much in advance!

**Comment by Restricted-Memory** [comment]
> Hi! It seems like I am getting error when running ./eval_vost.sh with "model="r50_deaotl" and checkpoint path set to "--ckpt_path pretrain_models/aotplus_R50_DeOTL_Temp_pe_Slot_4_ema_20000.pth", “Traceback (most recent call last): File "/usr/local/lib/python3.8/dist-packages/torch/multiprocessing/spawn.py", line 69, in _wrap fn(i, *args) File "RMem/aot_plus/tools/eval.py", line 48, in main_worker evaluator.evaluating() File "RMem/aot_plus/./networks/managers/evaluator.py", line 475, in evaluating attn_values = np.reshape(lstt_layer.short_attn_values, (h, w, -1)) File "<**array_function** internals>", line 180, in reshape File "/usr/local/lib/python3.8/dist-packages/numpy/core/fromnumeric.py", line 298, in reshape return _wrapfunc(a, 'reshape', newshape, order=order) File "/usr/local/lib/python3.8/dist-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc return bound(*args, **kwds) ValueError: cannot reshape array of size 7200 into shape (37,66,newaxis)”
> 
> May I try to get suggestions c.f. how to solve this problem? Thank you so much in advance!

@MZhengRPI Sorry for my late reply. The code block should be commented out when evaluating, because these codes are for pilot study. I have update the code to fix this bug. Please check it. Thank you.

**Comment by MZhengRPI** [comment]
> > Hi! It seems like I am getting error when running ./eval_vost.sh with "model="r50_deaotl" and checkpoint path set to "--ckpt_path pretrain_models/aotplus_R50_DeOTL_Temp_pe_Slot_4_ema_20000.pth", “Traceback (most recent call last): File "/usr/local/lib/python3.8/dist-packages/torch/multiprocessing/spawn.py", line 69, in _wrap fn(i, *args) File "RMem/aot_plus/tools/eval.py", line 48, in main_worker evaluator.evaluating() File "RMem/aot_plus/./networks/managers/evaluator.py", line 475, in evaluating attn_values = np.reshape(lstt_layer.short_attn_values, (h, w, -1)) File "<**array_function** internals>", line 180, in reshape File "/usr/local/lib/python3.8/dist-packages/numpy/core/fromnumeric.py", line 298, in reshape return _wrapfunc(a, 'reshape', newshape, order=order) File "/usr/local/lib/python3.8/dist-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc return bound(*args, **kwds) ValueError: cannot reshape array of size 7200 into shape (37,66,newaxis)”
> > May I try to get suggestions c.f. how to solve this problem? Thank you so much in advance!
> 
> @MZhengRPI Sorry for my late reply. The code block should be commented out when evaluating, because these codes are for pilot study. I have update the code to fix this bug. Please check it. Thank you.

Thank you so much!
